"""Describe your changes

Revision ID: 29915aa9f917
Revises: da457408134b
Create Date: 2025-06-19 19:40:58.986493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29915aa9f917'
down_revision = 'da457408134b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.drop_column('random')

    # ### end Alembic commands ###
