"""Describe your changes

Revision ID: 54b97d40cf61
Revises: 
Create Date: 2025-06-24 19:28:07.129795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b97d40cf61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caregiver_senior_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caregiver_id', sa.Integer(), nullable=False),
    sa.Column('senior_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['senior_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicine_reminder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_med_map_id', sa.Integer(), nullable=False),
    sa.Column('reminder_time', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_med_map_id'], ['user_med_map.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breakfast_before', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('breakfast_after', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lunch_before', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('lunch_after', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dinner_before', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dinner_after', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_taken')

    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_user_med_map_medicine_id', 'medicine', ['medicine_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_med_map_medicine_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'medicine', ['medicine_id'], ['id'])
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_taken', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('dinner_after')
        batch_op.drop_column('dinner_before')
        batch_op.drop_column('lunch_after')
        batch_op.drop_column('lunch_before')
        batch_op.drop_column('breakfast_after')
        batch_op.drop_column('breakfast_before')

    with op.batch_alter_table('medicine', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    op.drop_table('medicine_reminder')
    op.drop_table('caregiver_senior_map')
    # ### end Alembic commands ###
