"""rough part removed

Revision ID: 5c45d0b96add
Revises: 29915aa9f917
Create Date: 2025-06-20 18:25:54.980644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c45d0b96add'
down_revision = '29915aa9f917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.drop_column('random')
        batch_op.drop_column('had_taken')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_med_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('had_taken', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('random', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
