"""Caregiver_senior_map table updated

Revision ID: f786d8afce2d
Revises: 6f32c6516bcb
Create Date: 2025-06-20 22:10:07.111331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f786d8afce2d'
down_revision = '6f32c6516bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver_senior_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caregiver_senior_map', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
